salesforce:
  username: "![K4C4Axic0FW+R8t0GOS+dFGEsZfD4Zwd]"
  password: "![bBnnVPFiIavdanDCmcNfQw==]"
  token: "![Nk7XLuBuVCcsghlMOyZmbzKOGBtZbGeOKIjAV1NKMDc=]"

keystore:
  password: "![4A1ss200M1PLXL5WKHUtUQ==]"